infra: debugging deploy containers

diff --git a/.github/workflows/reusable-setup-testing-environment.yml b/.github/workflows/reusable-setup-testing-environment.yml
--- a/.github/workflows/reusable-setup-testing-environment.yml
+++ b/.github/workflows/reusable-setup-testing-environment.yml
@@ -105,69 +105,69 @@ jobs:
       #       --name ${{ vars.AUTH_APP_NAME }}-test-container \
       #       --image ${{ vars.CONTAINER_REGISTRY_NAME}}.azurecr.io/${{ vars.AUTH_APP_NAME }}:${{ inputs.image-tag }}
 
-      - name: Health Check Auth
-        run: |
-          RESPONSE=$(curl -s "http://${{ vars.AUTH_APP_NAME }}-test.eastus.azurecontainer.io:${{ vars.AUTH_PORT }}/health")
+      # - name: Health Check Auth
+      #   run: |
+      #     RESPONSE=$(curl -s "http://${{ vars.AUTH_APP_NAME }}-test.eastus.azurecontainer.io:${{ vars.AUTH_PORT }}/health")
           
-          if [[ "$RESPONSE" == *"Healthy"* ]]; then
-            echo "API is Healthy"
-          else
-            echo "API is not Healthy"
-            exit 1
-          fi
+      #     if [[ "$RESPONSE" == *"Healthy"* ]]; then
+      #       echo "API is Healthy"
+      #     else
+      #       echo "API is not Healthy"
+      #       exit 1
+      #     fi
 
-      - name: Deploy TechNews Core Container
-        uses: azure/cli@v1
-        with:
-          max_attempts: 1
-          retry_on: error
-          azcliversion: latest
-          inlineScript: |
-            az container create \
-            --resource-group ${{ vars.TEST_RESOURCE_GROUP_NAME }} \
-            --environment-variables \
-            TECHNEWS_CORE_API_DATABASE_CONNECTION_STRING="Server=tcp:dbs-technews-test-eastus.database.windows.net,1433;Initial Catalog=TechNewsTest;Persist Security Info=False;User ID=${{ secrets.ADMIN_LOGIN }};Password=${{ secrets.ADMIN_PASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" \
-            ASPNETCORE_URLS="http://+:${{ vars.CORE_PORT }}" \
-            TECHNEWS_CORE_API_AUTH_JWKS_URL="http://${{ vars.AUTH_APP_NAME }}-test.eastus.azurecontainer.io:${{ vars.AUTH_PORT }}/jwks" \
-            --memory 0.5 --cpu 1 --ports ${{ vars.CORE_PORT }} \
-            --ip-address Public \
-            --dns-name-label ${{ vars.CORE_APP_NAME }}-test \
-            --registry-login-server ${{ vars.CONTAINER_REGISTRY_NAME}}.azurecr.io \
-            --registry-username "anonymous" \
-            --registry-password "anonymous" \
-            --name ${{ vars.CORE_APP_NAME }}-test-container \
-            --image ${{ vars.CONTAINER_REGISTRY_NAME}}.azurecr.io/${{ vars.CORE_APP_NAME }}:${{ inputs.image-tag }}
+      # - name: Deploy TechNews Core Container
+      #   uses: azure/cli@v1
+      #   with:
+      #     max_attempts: 1
+      #     retry_on: error
+      #     azcliversion: latest
+      #     inlineScript: |
+      #       az container create \
+      #       --resource-group ${{ vars.TEST_RESOURCE_GROUP_NAME }} \
+      #       --environment-variables \
+      #       TECHNEWS_CORE_API_DATABASE_CONNECTION_STRING="Server=tcp:dbs-technews-test-eastus.database.windows.net,1433;Initial Catalog=TechNewsTest;Persist Security Info=False;User ID=${{ secrets.ADMIN_LOGIN }};Password=${{ secrets.ADMIN_PASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" \
+      #       ASPNETCORE_URLS="http://+:${{ vars.CORE_PORT }}" \
+      #       TECHNEWS_CORE_API_AUTH_JWKS_URL="http://${{ vars.AUTH_APP_NAME }}-test.eastus.azurecontainer.io:${{ vars.AUTH_PORT }}/jwks" \
+      #       --memory 0.5 --cpu 1 --ports ${{ vars.CORE_PORT }} \
+      #       --ip-address Public \
+      #       --dns-name-label ${{ vars.CORE_APP_NAME }}-test \
+      #       --registry-login-server ${{ vars.CONTAINER_REGISTRY_NAME}}.azurecr.io \
+      #       --registry-username "anonymous" \
+      #       --registry-password "anonymous" \
+      #       --name ${{ vars.CORE_APP_NAME }}-test-container \
+      #       --image ${{ vars.CONTAINER_REGISTRY_NAME}}.azurecr.io/${{ vars.CORE_APP_NAME }}:${{ inputs.image-tag }}
       
-      - name: Health Check Core
-        run: |
-          RESPONSE=$(curl -s "http://${{ vars.CORE_APP_NAME }}-test.eastus.azurecontainer.io:${{ vars.CORE_PORT }}/health")
+      # - name: Health Check Core
+      #   run: |
+      #     RESPONSE=$(curl -s "http://${{ vars.CORE_APP_NAME }}-test.eastus.azurecontainer.io:${{ vars.CORE_PORT }}/health")
           
-          if [[ "$RESPONSE" == *"Healthy"* ]]; then
-            echo "API is Healthy"
-          else
-            echo "API is not Healthy"
-            exit 1
-          fi
+      #     if [[ "$RESPONSE" == *"Healthy"* ]]; then
+      #       echo "API is Healthy"
+      #     else
+      #       echo "API is not Healthy"
+      #       exit 1
+      #     fi
 
 
-      - name: Deploy TechNews Web Container
-        uses: azure/cli@v1
-        with:
-          max_attempts: 1
-          retry_on: error
-          azcliversion: latest
-          inlineScript: |
-            az container create \
-            --resource-group ${{ vars.TEST_RESOURCE_GROUP_NAME }} \
-            --environment-variables \
-            TECHNEWS_APP_API_AUTH_URL="http://${{ vars.AUTH_APP_NAME }}-test.eastus.azurecontainer.io:${{ vars.AUTH_PORT }}" \
-            TECHNEWS_APP_API_CORE_URL="http://${{ vars.CORE_APP_NAME }}-test.eastus.azurecontainer.io:${{ vars.CORE_PORT }}" \
-            ASPNETCORE_URLS="http://+:${{ vars.WEB_PORT }}" \
-            --memory 0.5 --cpu 1 --ports ${{ vars.WEB_PORT }} \
-            --ip-address Public \
-            --dns-name-label ${{ vars.WEB_APP_NAME }}-test \
-            --registry-login-server ${{ vars.CONTAINER_REGISTRY_NAME}}.azurecr.io \
-            --registry-username "anonymous" \
-            --registry-password "anonymous" \
-            --name ${{ vars.WEB_APP_NAME }}-test-container \
-            --image ${{ vars.CONTAINER_REGISTRY_NAME}}.azurecr.io/${{ vars.WEB_APP_NAME }}:${{ inputs.image-tag }}
+      # - name: Deploy TechNews Web Container
+      #   uses: azure/cli@v1
+      #   with:
+      #     max_attempts: 1
+      #     retry_on: error
+      #     azcliversion: latest
+      #     inlineScript: |
+      #       az container create \
+      #       --resource-group ${{ vars.TEST_RESOURCE_GROUP_NAME }} \
+      #       --environment-variables \
+      #       TECHNEWS_APP_API_AUTH_URL="http://${{ vars.AUTH_APP_NAME }}-test.eastus.azurecontainer.io:${{ vars.AUTH_PORT }}" \
+      #       TECHNEWS_APP_API_CORE_URL="http://${{ vars.CORE_APP_NAME }}-test.eastus.azurecontainer.io:${{ vars.CORE_PORT }}" \
+      #       ASPNETCORE_URLS="http://+:${{ vars.WEB_PORT }}" \
+      #       --memory 0.5 --cpu 1 --ports ${{ vars.WEB_PORT }} \
+      #       --ip-address Public \
+      #       --dns-name-label ${{ vars.WEB_APP_NAME }}-test \
+      #       --registry-login-server ${{ vars.CONTAINER_REGISTRY_NAME}}.azurecr.io \
+      #       --registry-username "anonymous" \
+      #       --registry-password "anonymous" \
+      #       --name ${{ vars.WEB_APP_NAME }}-test-container \
+      #       --image ${{ vars.CONTAINER_REGISTRY_NAME}}.azurecr.io/${{ vars.WEB_APP_NAME }}:${{ inputs.image-tag }}
